In [9]:
import tensorflow.compat.v2.feature_column as fc
import tensorflow as tf

import numpy as np
import pandas as pd
import sklearn
print(tf.__version__)

2.10.0


In [10]:
print(tf.config.list_physical_devices('GPU'))
# checks for GPU usage

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [11]:
print(tf.reduce_sum(tf.random.normal([1000, 1000])))
# checks for CPU usage

tf.Tensor(-272.64862, shape=(), dtype=float32)


In [13]:
a = tf.Variable(324.0, dtype=tf.float64)
print(a)

<tf.Variable 'Variable:0' shape=() dtype=float64, numpy=324.0>


In [33]:
rank1_tensor = tf.Variable([1.0,2], dtype=tf.float16)
print(rank1_tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=float16, numpy=array([1., 2.], dtype=float16)>


In [34]:
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [38]:
rank1_tensor.shape

TensorShape([2])

In [41]:
a = tf.reshape(rank1_tensor, [1,2])
print(a)

tf.Tensor([[1. 2.]], shape=(1, 2), dtype=float16)


In [46]:
t = tf.ones([5,5,5,5])
print(t)
t_one = tf.reshape(t,[5,-1])
print(t_one)

tf.Tensor(
[[[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1.

In [12]:
dftrain  = pd.read_csv("https://storage.googleapis.com/tf-datasets/titanic/train.csv")
pd.read_csv("https://storage.googleapis.com/tf-datasets/titanic/eval.csv"